/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.SingleFadeAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

/** Subsystem that controls an addressable LED strip using a CANdle. */
public class LEDSubsystem extends SubsystemBase {
  private final CANBus kCANBus = new CANBus("rio");
  private final CANdle m_candle = new CANdle(60, kCANBus);

  private final SingleFadeAnimation m_slot0Animation =
      new SingleFadeAnimation(8, 300)
          .withSlot(0)
          .withColor(new RGBWColor(255, 50, 0, 0))
          .withFrameRate(Hertz.of(100));

  private final SolidColor[] m_colors =
      new SolidColor[] {
        new SolidColor(0, 7).withColor(new RGBWColor(255, 255, 255, 0)),
      };

  public LEDSubsystem() {
    setDefaultCommand(updateLEDs());
  }

  /**
   * Updates the animations and LEDs of the CANdle.
   *
   * @return Command to run
   */
  public Command updateLEDs() {
    return run(
        () -> {
          for (var solidColor : m_colors) {
            m_candle.setControl(solidColor);
          }
          m_candle.setControl(m_slot0Animation);
        });
  }
}

// TODO: LEDs turn on when robot is enabled and stay on when robot is disabled, find a way to turn on/off LEDs when robot is enabled/disabled
